---
provisioner:
  name: chef_solo
  attributes:
    omnibus_updater:
      disabled: true
    osl-php:
      packages:
          - 'php'
          - 'php-devel'
          - 'php-fpm'
          - 'php-gd'
          - 'php-pear'

suites:
  - name: default
    run_list:
      - recipe[osl-php::default]
  - name: apc
    run_list:
      - recipe[osl-php::default]
      - recipe[osl-php::apc]
    attributes:
      osl-php:
        apc:
          shm_size: '128M'
  - name: composer
    run_list:
    - recipe[osl-php::composer]
  - name: packages
    run_list:
    - recipe[osl-php::packages]
