---
provisioner:
  name: chef_solo
  attributes:
    omnibus_updater:
      disabled: true
    osl-php:
      php_packages:
        - 'devel'
        - 'fpm'
        - 'gd'

suites:
  - name: default
    run_list:
      - recipe[osl-php::default]
  - name: apc
    run_list:
      - recipe[osl-php::default]
      - recipe[osl-php::apc]
    attributes:
      osl-php:
        apc:
          shm_size: '128M'
  - name: composer
    run_list:
    - recipe[osl-php::composer]
  - name: packages
    run_list:
    - recipe[osl-php::packages]
  - name: packages-php56
    run_list:
    - recipe[osl-php::packages]
    attributes:
      osl-php:
        use_ius: true
      php:
        version: '5.6'
  - name: packages-php70
    run_list:
    - recipe[osl-php::packages]
    attributes:
      osl-php:
        use_ius: true
      php:
        version: '7.0'
  - name: packages-php71
    run_list:
    - recipe[osl-php::packages]
    attributes:
      osl-php:
        use_ius: true
      php:
        version: '7.1'
  - name: packages-php72
    run_list:
    - recipe[osl-php::packages]
    attributes:
      osl-php:
        use_ius: true
      php:
        version: '7.2'
    excludes:
      - centos-6.9
