---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    attributes:
      osl-php:
       packages:
           apc:
             php-apc: false
           allthepackages:
             - php5-fpm
             - php5-gd
    run_list:
      - recipe[apt]
  - name: centos-6.5
    attributes:
      osl-php:
       packages:
         apc:
             php-apc: false
         moar_packages:
           - php-fpm
           - php-gd

suites:
  - name: default
    run_list:
      - recipe[osl-php::default]
    attributes:
  - name: apc
    run_list:
        - recipe[build-essential]
        - recipe[osl-php::default]
        - recipe[osl-php::apc]
    attributes:
        osl-php:
            packages:
                php-apc: true
            apc:
                shm_size: 128M
