AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'

Metrics/AbcSize:
  Max: 9001

Style/IfUnlessModifierOfIfUnless:
  Exclude:
    - 'libraries/collect_packages.rb'
