name             'osl-php'
maintainer       'Anthony Miller'
maintainer_email 'armiller@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/osl-php'
issues_url       'https://github.com/osuosl-cookbooks/osl-php/issues'
license          'Apache-2.0'
chef_version     '>= 14.0'
description      'Installs/Configures osl-php'
long_description 'Installs/Configures osl-php'
version          '5.0.1'

supports         'centos', '~> 8.0'
supports         'centos', '~> 7.0'
supports         'centos', '~> 6.0'

depends          'composer'
depends          'php', '~> 6.1.1'
depends          'yum-centos'
depends          'yum-ius', '~> 3.1.0'
depends          'yum-osuosl'
