#!/bin/bash

SEARCHDIR=/var/www

function show_help () {
  cat <<- "  EOH"
	phpshow help:

	ARGUMENTS:
	  -h:     show this help message
	  -d DIR: look in DIR instead of current directory

	USAGE:
	  phpshow -d DIR 'regex'

	phpcheck and phpshow are a couple of aliases to check a directory's php files for a regex expression.
	These are intended to help find depreciated functions, etc.

	phpcheck will show just the immediate subdirs that have files that match the regex.
	phpshow will show all offending lines, but can be hard to deciper if there are a lot of matches.

	Recommended use is:
	- use phpcheck in /var/www/ to find sites with problems
	- use phpshow in individual webroots to see some context around each match

	Note: 'geshi' directories are excluded as Geshi is a syntax highlighter and will most likely
	throw false positives from its php highlighting.
  EOH

  exit 0
}

while getopts ":hd:" opt; do
  case $opt in
    h)
      show_help
      ;;
    d)
      SEARCHDIR="$OPTARG"
      ;;
    *)
      ;;
  esac
done
shift $((OPTIND -1)) # remove args handled by getopt

find "$SEARCHDIR" -type f -name '*.php' -or -name '*.ini' | grep -v '/geshi/' | xargs grep --color=auto -HnT -e "$*"
